repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(artifacts|data|models|results)/'
      - id: end-of-file-fixer
        exclude: '^(artifacts|data|models|results)/'
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: check-added-large-files
        exclude: '^(artifacts|data|models|results)/|\\.ipynb$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
        additional_dependencies: []
        exclude: '.*\.ipynb$'

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-q", "-c", "pyproject.toml"]
        files: '^.*\.py$'

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--ignore-words-list=te,hist"]
        exclude: '.*\.ipynb$'

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: '\.(yaml|yml)$'
        args: ["-d", "{extends: default, rules: {line-length: disable}}"]

  # Hadolint via Docker image; mark as manual to avoid requiring Docker during normal commits
  - repo: local
    hooks:
      - id: hadolint
        name: hadolint (Dockerfile lint)
        language: docker_image
        entry: ghcr.io/hadolint/hadolint:latest hadolint
        files: '(^|/)Dockerfile$|(^|/)docker/.*Dockerfile$'
        stages: [manual]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: '^(\.venv|\.uv-cache|artifacts|reports|data)/'
        stages: [manual]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: '.*\.ipynb$'

ci:
  autofix_prs: true
  skip: [detect-secrets]
